name=input("enter your name: ")
course=input("enter your course name: ")
rollno=int(input("enter your roll no.: "))
dob=input("enter your dob: ")
print(name)
print(course)
print(rollno)
print(dob)
